import React from "react"; 

function FeedbackComp() {
    return(
        //success or error 
        <div className="msg-container">
            {/* <div class="logo">
            {{getOrg()}}
        </div>

        <div class="marquee">
            Certificate of {this.state.cert}

        </div>

        <div class="assignment">
            This certificate is presented to
        </div>

        <div class="person">
            {this.state.first_name} {this.state.last_name}
        </div>

        <div class="date">
            On this <span>{{day}}</span> day of the month {{month}} of the year {{year}}
            {{getDate()}}
        </div>

        <div class="reason">
            for {{getReason()}}
        </div>

        <div class="witness">
            witnessed by {{getWitnessFullName()}}
            <div class="signed"></div>
        </div>
    <p>generated by I-Was-There!</p> */}
        </div>
    ); 
}
export default FeedbackComp; 